GRANT SELECT, INSERT, UPDATE ON TABLE public.student_profiles TO authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE public.parent_profiles TO authenticated;
GRANT SELECT ON TABLE public.student_parent_links TO authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE public.nex_message_flags TO service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE public.coupons TO service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE public.beta_invites TO service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE public.admin_support_cases TO service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE public.admin_feature_rollouts TO service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE public.mpesa_payments TO service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE public.topic_mastery TO service_role;
GRANT SELECT ON TABLE public.nex_sessions TO service_role;
GRANT SELECT ON TABLE public.nex_messages TO service_role;
GRANT SELECT ON TABLE public.practice_sessions TO service_role;
GRANT SELECT ON TABLE public.subscription_trials TO service_role;
GRANT SELECT ON TABLE public.curricula TO service_role;
GRANT SELECT ON TABLE public.subjects TO service_role;
GRANT SELECT ON TABLE public.topics TO service_role;
GRANT SELECT ON TABLE public.subtopics TO service_role;
GRANT SELECT ON TABLE public.lessons TO service_role;
GRANT SELECT ON TABLE public.practice_questions TO service_role;

REVOKE ALL ON TABLE public.student_profiles FROM anon;
REVOKE ALL ON TABLE public.parent_profiles FROM anon;
REVOKE ALL ON TABLE public.student_parent_links FROM anon;
REVOKE ALL ON TABLE public.beta_invites FROM anon;
REVOKE ALL ON TABLE public.admin_support_cases FROM anon;
REVOKE ALL ON TABLE public.admin_feature_rollouts FROM anon;
REVOKE ALL ON TABLE public.mpesa_payments FROM anon;
REVOKE ALL ON TABLE public.topic_mastery FROM anon;
REVOKE ALL ON TABLE public.nex_sessions FROM anon;
REVOKE ALL ON TABLE public.nex_messages FROM anon;
REVOKE ALL ON TABLE public.practice_sessions FROM anon;
REVOKE ALL ON TABLE public.subscription_trials FROM anon;
REVOKE ALL ON TABLE public.curricula FROM anon;
REVOKE ALL ON TABLE public.subjects FROM anon;
REVOKE ALL ON TABLE public.topics FROM anon;
REVOKE ALL ON TABLE public.subtopics FROM anon;
REVOKE ALL ON TABLE public.lessons FROM anon;
REVOKE ALL ON TABLE public.practice_questions FROM anon;
